version: 2.1

orbs:
  architect: giantswarm/architect@6.2.1

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: fulfillment
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: architect
          requires:
            - push-to-registries
          name: push-to-app-catalog
          executor: app-build-suite
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "fulfillment"
          filters:
            tags:
              only: /^v.*/
