apiVersion: v2
description: A Helm chart for fulfillment
home: https://github.com/giantswarm/fulfillment
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
keywords:
  - fulfillment
  - marketplace
  - aws
  - webhook
name: fulfillment
version: 0.0.5
appVersion: 0.0.5
annotations:
  io.giantswarm.application.team: "planeteers"
